- name: NGINX | Ensure nginx repo is available
  copy:
    src: files/etc/yum.repos.d/nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
  tags:
  - nginx
- name: NGINX | Ensure nginx is installed
  yum:
    name: nginx
    state: latest
  notify:
  - nginx.restart
  tags:
  - nginx
- name: NGINX | Ensure default.conf is available
  template:
    src: files/etc/nginx/conf.d/default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - nginx.restart
  tags:
  - nginx
- name: NGINX | Ensure nginx.conf is available
  copy:
    src: files/etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - nginx.restart
  tags:
  - nginx
- name: NGINX | Ensure cache folder exists
  file:
    path: /var/lib/nginx/cache
    owner: nginx
    group: nginx
    state: directory
    mode: 0777
  tags:
  - nginx
- name: NGINX | Ensure nginx starts on boot
  service:
    name: nginx
    enabled: yes
  tags:
  - nginx
- name: SECURITY | Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  tags:
  - nginx
